[env:nucleo_l432kc]
platform = ststm32
board = nucleo_l432kc
framework = stm32cube
monitor_speed = 115200
 
build_flags =
    -DSTM32L432xx
    -DUSE_HAL_DRIVER
 
upload_protocol = stlink
debug_tool = stlink
